// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1intmylSN64TfR5SpAKTProiiWT0YFzo',
    appId: '1:309428131314:web:9c318ee3ec0b7a94fa076b',
    messagingSenderId: '309428131314',
    projectId: 'byte-e6f0c',
    authDomain: 'byte-e6f0c.firebaseapp.com',
    storageBucket: 'byte-e6f0c.appspot.com',
    measurementId: 'G-H4KH93S5QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1bXqUdT1YA6-qPyOmtMuyg4nKPReZ0Yw',
    appId: '1:309428131314:android:223c93e02508a02bfa076b',
    messagingSenderId: '309428131314',
    projectId: 'byte-e6f0c',
    storageBucket: 'byte-e6f0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-W9x2bEoEwYkdQDKorHFM_cVmSXDI54',
    appId: '1:309428131314:ios:4b18c4f54b624f8afa076b',
    messagingSenderId: '309428131314',
    projectId: 'byte-e6f0c',
    storageBucket: 'byte-e6f0c.appspot.com',
    iosBundleId: 'com.example.byteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-W9x2bEoEwYkdQDKorHFM_cVmSXDI54',
    appId: '1:309428131314:ios:7f1859b33cb0b60afa076b',
    messagingSenderId: '309428131314',
    projectId: 'byte-e6f0c',
    storageBucket: 'byte-e6f0c.appspot.com',
    iosBundleId: 'com.example.byteApp.RunnerTests',
  );
}
